### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by qblol** [sepiropht/frontend-master-downloader#5]
I can't download some course, like svg-animation. The error was like this 

> (node:8792) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.navigate): Invalid parameters url: string value expected

> (node:8792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can you help me? thanks.

**Comment by sepiropht** [comment]
which platform do you use ?

**Comment by qblol** [comment]
I'm using ubuntu 18.04, node 8.9.4, and npm 6.10. Yes, in some courses it worked perfectly. Is there any restrictions after several downloads? sorry for my broken english.

**Comment by sepiropht** [comment]
Yeah there is restriction, but normally my script can handle it. How many constitutives courses do you download ? I will tried to reproduce the bug.

**Comment by qblol** [comment]
Hmm, maybe 5 to 10 courses per day. OK then, I'll try again.

**Comment by djohnson501** [comment]
I'm having the same issue. I've tried quite a few times in a row, so I'm going to give it a break for a few hours and see if that helps.

I'm also having trouble locating the correct course name. I'm trying to download the [Complete Intro to React](https://frontendmasters.com/courses/react/) but when I use `-c react ` it tries to download the [Reactive Angular](https://frontendmasters.com/courses/reactive-angular/) course. Any thoughts on that?

**Comment by sepiropht** [comment]
@djohnson501  i saw the issue with the two course. It happens because i'm not parsing the URL before doing the check. So i have to do include instead of  === for the two string. Sadly include work for react and reactive.  
I 'can't fix it know , but if you want you can fix and i can help to do that. It's pretty easy.

For the others problems, i never succed to reproduce them on my own machine. So i can't fix them. 
But i know that on windows it doesn't work at all.  And even in differents linux version, it have some problem. I never succes to run it on archlinux. This is a puppeter issue.

**Comment by djohnson501** [comment]
@sepiropht I'd love to help fix it if you could provide some guidance. I'm assuming the issue is on line 42 of crawler.js?

**Comment by sepiropht** [comment]
Yes exact! Actually the value of text is 'https://frontendmasters.com/courses/react/' you should transform it to have 'react' instead. And then replace 'include' by a strict equality between obj.course and text.
I hope i have been clear.
